[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=/Users/fiat/Developer/personal-projects/course-platform/node_modules/@openzeppelin/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
